ARRAYS

تعریف متغیر

In [2]:
a = 4

a = 4


In [3]:
d = .2

d = 0.2000


In [4]:
g = 2.36743

g = 2.3674


نماد;

In [6]:
s = 5.69;

In [7]:
f = s + 1

f = 6.6900


نماد ،

In [8]:
d = 2,e = 12;

d = 2


In [9]:
a =1 , b =2 , c = 3

a = 1
b = 2
c = 3


نمادe

In [11]:
20000000000

ans = 2.0000e+10


e + 10 ~ 10 ^ 10

In [17]:
1000e-3

ans = 1


برخی نماد ها

In [18]:
pi

ans = 3.1416


In [19]:
i

ans =  0 + 1i


In [20]:
j

ans =  0 + 1i


In [21]:
eps

ans = 2.2204e-16


In [22]:
inf

ans = Inf


In [23]:
nan

ans = NaN


In [24]:
0/0

ans = NaN


In [25]:
1/0

ans = Inf


نمایش تمام کلمات کلیدی متلب

In [26]:
iskeyword

ans =
{
  [1,1] = __FILE__
  [2,1] = __LINE__
  [3,1] = break
  [4,1] = case
  [5,1] = catch
  [6,1] = classdef
  [7,1] = continue
  [8,1] = do
  [9,1] = else
  [10,1] = elseif
  [11,1] = end
  [12,1] = end_try_catch
  [13,1] = end_unwind_protect
  [14,1] = endclassdef
  [15,1] = endenumeration
  [16,1] = endevents
  [17,1] = endfor
  [18,1] = endfunction
  [19,1] = endif
  [20,1] = endmethods
  [21,1] = endparfor
  [22,1] = endproperties
  [23,1] = endswitch
  [24,1] = endwhile
  [25,1] = for
  [26,1] = function
  [27,1] = global
  [28,1] = if
  [29,1] = otherwise
  [30,1] = parfor
  [31,1] = persistent
  [32,1] = return
  [33,1] = switch
  [34,1] = try
  [35,1] = until
  [36,1] = unwind_protect
  [37,1] = unwind_protect_cleanup
  [38,1] = while
}



کامنت گذاری

In [27]:
%سلام

اعداد مختلط

In [28]:
2 + 3i

ans =  2 + 3i


In [30]:
.45 + 3.8i

ans =  0.4500 + 3.8000i


In [31]:
4 + 3 * i

ans =  4 + 3i


In [32]:
4 + i3

error: 'i3' undefined near line 1, column 1


In [33]:
i = 10;4 + 3 * i

ans = 34


In [34]:
i = 10;4 + 3 * 1i

ans =  4 + 3i


آرایه ها

In [35]:
a = [2,5,8]

a =

   2   5   8



In [36]:
b = [2 -9 1.36 5.2 6.9]

b =

   2.0000  -9.0000   1.3600   5.2000   6.9000



In [37]:
d = [] %ماتریس تهی

d = [](0x0)


تعریف عنصر به عنصر آرایه

In [39]:
c(1) = 2;c(2) = 5;c(3) = 8;
c

c =

   2   5   8



In [40]:
%اندیس ها در متلب اعداد طبیعی هستند

In [41]:
%هرگاه عنصری را در آرایه مقدار دهی نکنیم به صورت پیشفرض صفر در نظر گرفته می شود

In [42]:
f(1) =5;f(2) = 8;f(6) = -5;
f

f =

   5   8   0   0   0  -5



آرایه های منظم

In [43]:
c = 1:5

c =

   1   2   3   4   5



In [44]:
c1 = 0 : 6

c1 =

   0   1   2   3   4   5   6



In [45]:
c2 = -6 : 9

c2 =

  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7   8   9



In [46]:
d1 = 0:2:10 %اعداد 0 تا 10 با گام های 2 تایی

d1 =

    0    2    4    6    8   10



In [47]:
d2 = 0:.2:10

d2 =

 Columns 1 through 7:

          0     0.2000     0.4000     0.6000     0.8000     1.0000     1.2000

 Columns 8 through 14:

     1.4000     1.6000     1.8000     2.0000     2.2000     2.4000     2.6000

 Columns 15 through 21:

     2.8000     3.0000     3.2000     3.4000     3.6000     3.8000     4.0000

 Columns 22 through 28:

     4.2000     4.4000     4.6000     4.8000     5.0000     5.2000     5.4000

 Columns 29 through 35:

     5.6000     5.8000     6.0000     6.2000     6.4000     6.6000     6.8000

 Columns 36 through 42:

     7.0000     7.2000     7.4000     7.6000     7.8000     8.0000     8.2000

 Columns 43 through 49:

     8.4000     8.6000     8.8000     9.0000     9.2000     9.4000     9.6000

 Columns 50 and 51:

     9.8000    10.0000



In [48]:
d3 = 0:-1:-3

d3 =

   0  -1  -2  -3



In [49]:
%برای حالت نزولی،گام منفی حتما باید ذکر شود وگرنه تهی خواهد بود

In [51]:
linspace(1,2,6) %بازه ی 1 تا 2 را به 6 قسمت مساوی تقسیم می کند و کران های بازه ها را چاپ می کند

ans =

   1.0000   1.2000   1.4000   1.6000   1.8000   2.0000



In [52]:
zeros(1,3) %برداری سه تایی از صفر می سازد

ans =

  0  0  0



In [53]:
ones(1,3) % برداری سه تایی از یک می سازد

ans =

   1   1   1



In [54]:
5 * ones(1,3) %برداری سه تایی از پنج می سازد

ans =

   5   5   5



اعداد و آرایه های تصادفی

In [56]:
rand(1,10) %آرایه ای از 10 عنصر با توزیع یکنواخت در بازه 0 تا 1 

ans =

 Columns 1 through 8:

   0.4511   0.8106   0.6464   0.6237   0.8475   0.9250   0.5845   0.1793

 Columns 9 and 10:

   0.2263   0.3578



In [57]:
8*rand(1,3)%برای گسترش بازه می توان تابع را در عددی ضرب کرد

ans =

   3.9751   7.3687   5.4172



In [58]:
randn(1,4) %تولید چهار عدد تصادفی با توزیع نرمال

ans =

   0.884487  -0.012691  -0.193382   1.083285



In [61]:
randperm(8) %اعداد 1-8 را به طور تصادفی مرتب می کند

ans =

   1   6   8   4   7   5   2   3



فراخوانی و مقدار دهی آرایه ها

In [62]:
a(3) %فراخوانی عنصر سوم 

ans = 8


In [63]:
a(0) %تعریف نشده

error: a(0): subscripts must be either integers 1 to (2^63)-1 or logicals


In [65]:
a(1:2) %فراخوانی چند مقدار

ans =

   2   5



In [69]:
a = 15 * rand(1,15);
a(2:5)
a(5:-1:2)
a(end)%آخرین جمله

ans =

   3.5778e+00   9.1009e-02   1.0260e+01   1.2137e+01



ans =

   1.2137e+01   1.0260e+01   9.1009e-02   3.5778e+00



ans = 13.206


In [70]:
a(end - 3) %جمله ی سه تا مانده به آخر

ans = 5.5558


In [71]:
a(3:end) %از سومین جمله به بعد

ans =

 Columns 1 through 6:

   9.1009e-02   1.0260e+01   1.2137e+01   3.6534e+00   6.2604e+00   2.1312e+00

 Columns 7 through 12:

   1.3263e+01   1.1252e+01   4.9706e+00   5.5558e+00   4.8195e+00   1.4550e+01

 Column 13:

   1.3206e+01



In [72]:
a(end:-1:1) %از آخر به اول

ans =

 Columns 1 through 6:

   1.3206e+01   1.4550e+01   4.8195e+00   5.5558e+00   4.9706e+00   1.1252e+01

 Columns 7 through 12:

   1.3263e+01   2.1312e+00   6.2604e+00   3.6534e+00   1.2137e+01   1.0260e+01

 Columns 13 through 15:

   9.1009e-02   3.5778e+00   9.1450e+00



In [74]:
a(:) % از اول تا آخر به صورت ستونی

ans =

   9.1450e+00
   3.5778e+00
   9.1009e-02
   1.0260e+01
   1.2137e+01
   3.6534e+00
   6.2604e+00
   2.1312e+00
   1.3263e+01
   1.1252e+01
   4.9706e+00
   5.5558e+00
   4.8195e+00
   1.4550e+01
   1.3206e+01



In [75]:
a([2 7]) %عنصر دوم و هفتم

ans =

   3.5778   6.2604



In [77]:
a(c(1)) % اولین جمله ی بردار سی را محاسبه کرده و جمله ای از آ که اندیسش آن عدد باشد را نمایش می دهد

ans = 9.1450


In [78]:
a(c)

ans =

   9.1450e+00   3.5778e+00   9.1009e-02   1.0260e+01   1.2137e+01



In [79]:
a(d)

ans = [](0x0)


In [80]:
a([c d 2])

ans =

   9.1450e+00   3.5778e+00   9.1009e-02   1.0260e+01   1.2137e+01   3.5778e+00



مقداردهی آرایه ها

In [81]:
a(1:3) = [1 1 1]

a =

 Columns 1 through 8:

    1.0000    1.0000    1.0000   10.2599   12.1370    3.6534    6.2604    2.1312

 Columns 9 through 15:

   13.2629   11.2525    4.9706    5.5558    4.8195   14.5504   13.2062



In [82]:
a([2 7]) = [77 77]

a =

 Columns 1 through 8:

    1.0000   77.0000    1.0000   10.2599   12.1370    3.6534   77.0000    2.1312

 Columns 9 through 15:

   13.2629   11.2525    4.9706    5.5558    4.8195   14.5504   13.2062



In [83]:
x = a

x =

 Columns 1 through 8:

    1.0000   77.0000    1.0000   10.2599   12.1370    3.6534   77.0000    2.1312

 Columns 9 through 15:

   13.2629   11.2525    4.9706    5.5558    4.8195   14.5504   13.2062



In [85]:
x(1) = [] %حذف عنصر

x =

 Columns 1 through 8:

    1.0000   10.2599   12.1370    3.6534   77.0000    2.1312   13.2629   11.2525

 Columns 9 through 13:

    4.9706    5.5558    4.8195   14.5504   13.2062



In [86]:
x(1:3) = []

x =

 Columns 1 through 8:

    3.6534   77.0000    2.1312   13.2629   11.2525    4.9706    5.5558    4.8195

 Columns 9 and 10:

   14.5504   13.2062



In [87]:
x(1:2:end)

ans =

    3.6534    2.1312   11.2525    5.5558   14.5504



In [88]:
a

a =

 Columns 1 through 8:

    1.0000   77.0000    1.0000   10.2599   12.1370    3.6534   77.0000    2.1312

 Columns 9 through 15:

   13.2629   11.2525    4.9706    5.5558    4.8195   14.5504   13.2062

